# Generated by Django 5.2.17 on 2026-09-20 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "base_unit",
                    models.CharField(choices=[("g", "г"), ("ml", "мл")], max_length=2),
                ),
                ("calories", models.DecimalField(decimal_places=1, max_digits=7)),
                ("proteins", models.DecimalField(decimal_places=1, max_digits=7)),
                ("fats", models.DecimalField(decimal_places=1, max_digits=7)),
                ("carbs", models.DecimalField(decimal_places=1, max_digits=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
