# Generated by Django 5.2.17 on 2026-09-20 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_products"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Завтрак"),
                            ("second_breakfast", "Второй завтрак"),
                            ("lunch", "Обед"),
                            ("afternoon_snack", "Полдник"),
                            ("dinner", "Ужин"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=1, max_digits=7)),
                (
                    "calories_snapshot",
                    models.DecimalField(decimal_places=1, max_digits=7),
                ),
                (
                    "proteins_snapshot",
                    models.DecimalField(decimal_places=1, max_digits=7),
                ),
                ("fats_snapshot", models.DecimalField(decimal_places=1, max_digits=7)),
                ("carbs_snapshot", models.DecimalField(decimal_places=1, max_digits=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diary_entries",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "diary entries",
                "ordering": ["created_at"],
            },
        ),
    ]
