# Generated by Django 5.2.17 on 2026-09-20 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_diaryentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calories", models.DecimalField(decimal_places=1, max_digits=7)),
                ("proteins", models.DecimalField(decimal_places=1, max_digits=7)),
                ("fats", models.DecimalField(decimal_places=1, max_digits=7)),
                ("carbs", models.DecimalField(decimal_places=1, max_digits=7)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_target",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
